# Generated by Django 3.2.3 on 2022-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0009_remove_client_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
